### ISSUE TITLE
Vulnerability hosts not remove

### ISSUE THREAD

**Issue by mattburch** [lair-framework/browser-scripts#22]
When running the Meteor.call function to remove hosts, the host information will manually need to be removed from each vulnerability it is linked to. The vulnerabilities maintain an isolated list of hosts that is looked up on the server side, when attempting to view hosts on a vulnerability that contains hosts that have been removed, no hosts are displayed.

**Comment by tomsteele** [comment]
https://github.com/lair-framework/browser-scripts/blob/master/delete_hosts_by_status.js#L16-L21

Are you suggesting that removeHostFromVulnerabilities be called in removeHost?

**Comment by mattburch** [comment]
Yea, I ran into an issue were I removed hosts with the script but was
unable to list hosts in the vulnerabilities because there were stale hosts
in the list. I have to walk through the host list and kill hosts that did
not exist in the project.

**Comment by mattburch** [comment]
Thks issue was filled to Patten's filter hosts script, right? That was were
I had meant to post it.

**Comment by tomsteele** [comment]
I don't know, i'll change the behavior in the next version of lair. Can you go through the browser scripts and just add the additional method call for now?

**Comment by mattburch** [comment]
Yea, no worries. Just wanted to file an issue

**Comment by tomsteele** [comment]
:+1: thanks

**Comment by tomsteele** [comment]
@mattburch to confirm, were you going to make the changes to each of the scripts?

**Comment by mattburch** [comment]
Confirmed. I will get the updates in.

**Comment by tomsteele** [comment]
Cool thanks @mattburch
